### ISSUE TITLE
Add HTTP endpoint with informations required for the top up scripts into the research bots

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/research#33]
We (ops) have tools to manage our internal bots, but We want to integrate the research bots and make them work on our infrastructure. To avoid rewriting scripts We would like to add one more endpoint for the research bot available on the HTTP protocol. The required endpoint is the one that returns some information about the market/assets the trader with a given `party ID` trades.

# Acceptance criteria

- A list of traders is available on the HTTP endpoint when bots are running
- Response for traders is a valid JSON output(may be other easy to parse format)
- Response provides the following data for each trader
    - Public Key
    - Asset to top-up
    - Maybe an amount of assets to the top would be nice

- It would be nice to provide the same format as below but endpoints but we can adjust our scripts for a better response structure

Example output for currently working endpoint you can find on the following URLs:

- https://traderbot-stagnet1-k8s.ops.vega.xyz/traders
- https://traderbot-fairground-k8s.ops.vega.xyz/traders
- https://traderbot-devnet1-k8s.ops.vega.xyz/traders

At the moment our script is using only the following information:
- `trader.Parameters.SettlementERC20TokenAddress`
- `trader.PubKey`

We ignore rest params during the topup procedure

For info We have topup implemented here: https://github.com/vegaprotocol/devopstools/blob/main/networktools/bots.go#L48

**Comment by Jiajia-Cui** [comment]
not the right repo @daniel1302
